# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ source ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ 12.20.0 ]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v2.1.3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Cache Hexo public
        uses: actions/cache@v2.1.3
        with:
          path: |
            **/public
            db.json
          key: ${{ runner.os }}-hexo-db}}
      - name: Install Dependencies
        run: |
          yarn install
      - name: Build
        run: |
          npx hexo g
          export HEXO_ALGOLIA_INDEXING_KEY=64ab79c7075e45cec5b1a0f3314ec6f5
          npx hexo algolia
      - name: SSH agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.BLOG_DEPLOY_KEY }}
      - name: Deploy VPS
        run: |
          ssh-keyscan 1991421.cn >> ~/.ssh/known_hosts
          rsync -az -vv --delete -e 'ssh -p 22' public/ root@1991421.cn:/var/www/blog/public-en/
      #      - name: Deploy GitHub
      #        uses: ad-m/github-push-action@master
      #        with:
      #          github_token: ${{ secrets.BLOG_DEPLOY_4_GITHUB_KEY }}
      #          branch: master
      #          directory: ./public
      #          force: true
      - name: Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Blog-en deployment and update completed, see [here](https://en.1991421.cn).
          format: markdown
